"""Typed structures for the market-making environment."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator

__all__ = [
    "MarketMakingAction",
    "MarketMakingEpisodeResult",
    "MarketMakingTaskParams",
    "Quote",
]


class MarketMakingTaskParams(BaseModel):
    """Public toy quote-decision task parameters.

    The fields intentionally describe a synthetic one-shot decision, not a live
    market state. Prices, risk limits, and arrival intensity are generated by the
    benchmark and are used only for deterministic evaluation.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    mid_price: float = Field(gt=0)
    inventory: float
    position_limit: float = Field(gt=0)
    max_daily_loss: float = Field(ge=0)
    current_daily_pnl: float
    volatility: float = Field(ge=0)
    spread: float = Field(gt=0)
    adverse_selection_risk: float = Field(ge=0, le=1)
    order_arrival_intensity: float = Field(gt=0)
    risk_aversion: float = Field(gt=0)
    recent_price_path: list[float] = Field(default_factory=list)
    max_quote_size: float = Field(default=5.0, gt=0)
    tick_size: float = Field(default=0.01, gt=0)
    candidate_actions: list[str] = Field(
        default_factory=lambda: ["quote_two_sided", "reduce_inventory", "abstain"]
    )


class MarketMakingAction(BaseModel):
    """Agent response for a market-making quote decision."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    bid_price: float | None = None
    ask_price: float | None = None
    bid_size: float = Field(default=0.0, ge=0)
    ask_size: float = Field(default=0.0, ge=0)
    reduce_inventory: bool = False
    abstain: bool = False
    confidence: float | None = Field(default=None, ge=0, le=1)
    reasoning_summary: str | None = None


class Quote(BaseModel):
    """A two-sided quote: a bid and an ask for a given size."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    bid: float
    ask: float
    size: float = Field(default=1.0, gt=0)

    @property
    def spread(self) -> float:
        return self.ask - self.bid

    @property
    def mid(self) -> float:
        return 0.5 * (self.ask + self.bid)


class MarketMakingEpisodeResult(BaseModel):
    """Summary statistics of a completed market-making episode."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    realized_pnl: float
    final_inventory: float
    min_inventory: float
    max_inventory: float
    n_quotes: int = Field(default=0, ge=0)

    @model_validator(mode="after")
    def _check_inventory_range(self) -> MarketMakingEpisodeResult:
        if self.min_inventory > self.max_inventory:
            raise ValueError("min_inventory must be <= max_inventory.")
        return self

    @property
    def max_abs_inventory(self) -> float:
        """The largest absolute inventory reached during the episode."""
        return max(abs(self.min_inventory), abs(self.max_inventory))
